In [13]:
import numpy as np
np1 = np.arange(1,18,2).reshape(3,3)
print(np1)
np.ndim(np1)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


2

In [14]:
np2 = np.random.rand(4,3)
print(np2)

[[0.82099761 0.04570719 0.37233435]
 [0.92153121 0.14669176 0.99038679]
 [0.92920092 0.52513425 0.71104497]
 [0.87544524 0.61018426 0.07907836]]


In [22]:
np3= np.random.randint(1,10,size=9).reshape(3,3)
print(np3)

[[2 1 6]
 [3 4 2]
 [2 5 3]]


In [25]:
np4 =np.arange(1,10,1)
print(np4)
np4 = np4.reshape(3,3)
print(np4)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
